In [1]:
import numpy as np
import pandas as pd
import csv

In [2]:
data = pd.read_csv('A:/PWR/project/AI/heart/heart.csv')
data.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

### testing training

In [3]:
x = data.drop(["target"],axis=1)
y = data["target"].values

In [4]:
# split train test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2, random_state=10)

In [5]:
x_train.shape, x_test.shape

((242, 13), (61, 13))

### distance

In [6]:
# find distance
def distance(a, b):
    a = np.array(a) 
    b = np.array(b)
    
    return np.linalg.norm(a - b)
#print(distance([3, 5, 4], [1, 1, 3]))


### voting

In [7]:
from collections import Counter
def claspred(neighbors):
    classCounter = Counter()
    for neighbor in neighbors:
        classCounter[neighbor] += 1
    return classCounter.most_common(1)[0][0]

### normal

In [8]:
with open('A:/PWR/project/AI/heart/distancenormal.csv', 'wb') as csvfile:
    spamwriter = csv.writer(csvfile, delimiter=',', quotechar='|', quoting=csv.QUOTE_MINIMAL)
    spamwriter.writerow(["index_test","index_train", "distance", "class_real","class_pred"])
    for index in range(len(x_test)):
        for ind in range(len(x_train)):
            dist = distance(x_test[index:index+1],x_train[ind:ind+1])
            spamwriter.writerow([index,ind, dist, y_test[index], y_train[ind]])

In [9]:
data2 = pd.read_csv('A:/PWR/project/AI/heart/distancenormal.csv')
data2.head()

index_test  index_train    distance  class_real  class_pred
0           0            0  205.409859           0           0
1           0            1  216.172639           0           1
2           0            2  198.302824           0           0
3           0            3  229.271128           0           1
4           0            4  232.590305           0           1

In [10]:
with open('A:/PWR/project/AI/heart/resultnormal.csv', 'wb') as csvfile:
    writer = csv.writer(csvfile, delimiter=',', quotechar='|', quoting=csv.QUOTE_MINIMAL)
    writer.writerow(["index_test", "class_real","class_pred"])
    for inde in range(len(x_test)):
        sort=data2[data2['index_test'] == inde].sort_values(by=['distance'], ascending=True)
        sort2=sort.iloc[0:6]
        clp = sort2.class_pred
        writer.writerow([inde, y_test[inde],claspred(clp)])


In [11]:
shownormal = pd.read_csv('A:/PWR/project/AI/heart/resultnormal.csv')
shownormal.head()

index_test  class_real  class_pred
0           0           0           1
1           1           0           0
2           2           0           0
3           3           1           1
4           4           0           0

In [39]:
predic=[]
for indexing in range(len(x_test)):
    sort=data2[data2['index_test'] == indexing].sort_values(by=['distance'], ascending=True)
    sort2=sort.iloc[0:6]
    clp=sort2.class_pred.values
    predic.append(claspred(clp))

#print(predic)


In [40]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, predic))

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, predic))
print(classification_report(y_test, predic))

0.7377049180327869
[[27  8]
 [ 8 18]]
              precision    recall  f1-score   support

           0       0.77      0.77      0.77        35
           1       0.69      0.69      0.69        26

   micro avg       0.74      0.74      0.74        61
   macro avg       0.73      0.73      0.73        61
weighted avg       0.74      0.74      0.74        61



### standard scaler

In [41]:
from sklearn.preprocessing import StandardScaler
st = StandardScaler()
x_training = st.fit_transform(x_train)
x_testing = st.fit_transform(x_test)

In [42]:
with open('A:/PWR/project/AI/heart/distancescaler.csv', 'wb') as csvfile:
    spamwriter = csv.writer(csvfile, delimiter=',', quotechar='|', quoting=csv.QUOTE_MINIMAL)
    spamwriter.writerow(["index_test","index_train", "distance", "class_real","class_pred"])
    for index in range(len(x_testing)):
        for ind in range(len(x_training)):
            dist = distance(x_testing[index:index+1],x_training[ind:ind+1])
            spamwriter.writerow([index,ind, dist, y_test[index], y_train[ind]])

In [43]:
data3 = pd.read_csv('A:/PWR/project/AI/heart/distancescaler.csv')

In [44]:
with open('A:/PWR/project/AI/heart/resultscaler.csv', 'wb') as csvfile:
    writer = csv.writer(csvfile, delimiter=',', quotechar='|', quoting=csv.QUOTE_MINIMAL)
    writer.writerow(["index_test", "class_real","class_pred"])
    for inde in range(len(x_testing)):
        sort=data3[data3['index_test'] == inde].sort_values(by=['distance'], ascending=True)
        sort2=sort.iloc[0:6]
        clp = sort2.class_pred
        writer.writerow([inde, y_test[inde],claspred(clp)])


In [45]:
cp=[]
for indekss3 in range(len(x_testing)):
    sort=data3[data3['index_test'] == indekss3].sort_values(by=['distance'], ascending=True)
    sort2=sort.iloc[0:6]
    clp=sort2.class_pred.values
    cp.append(claspred(clp))

    #print(clp)


In [46]:
print(accuracy_score(y_test, cp))
print(confusion_matrix(y_test, cp))
print(classification_report(y_test, cp))

0.7868852459016393
[[25 10]
 [ 3 23]]
              precision    recall  f1-score   support

           0       0.89      0.71      0.79        35
           1       0.70      0.88      0.78        26

   micro avg       0.79      0.79      0.79        61
   macro avg       0.79      0.80      0.79        61
weighted avg       0.81      0.79      0.79        61



### min-max normalization

In [47]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
x_training2 = scaler.fit_transform(x_train)
x_testing2 = scaler.fit_transform(x_test)

In [48]:
with open('A:/PWR/project/AI/heart/distanceminmax.csv', 'wb') as csvfile:
    spamwriter = csv.writer(csvfile, delimiter=',', quotechar='|', quoting=csv.QUOTE_MINIMAL)
    spamwriter.writerow(["index_test","index_train", "distance", "class_real","class_pred"])
    for index in range(len(x_testing2)):
        for ind in range(len(x_training2)):
            dist = distance(x_testing2[index:index+1],x_training2[ind:ind+1])
            spamwriter.writerow([index,ind, dist, y_test[index], y_train[ind]])

In [49]:
data4 = pd.read_csv('A:/PWR/project/AI/heart/distanceminmax.csv')

In [50]:
with open('A:/PWR/project/AI/heart/resultminmax.csv', 'wb') as csvfile:
    writer = csv.writer(csvfile, delimiter=',', quotechar='|', quoting=csv.QUOTE_MINIMAL)
    writer.writerow(["index_test", "class_real","class_pred"])
    for inde in range(len(x_testing)):
        sort=data4[data4['index_test'] == inde].sort_values(by=['distance'], ascending=True)
        sort2=sort.iloc[0:6]
        clp = sort2.class_pred
        writer.writerow([inde, y_test[inde],claspred(clp)])


In [51]:
cp2=[]
for indekss2 in range(len(x_testing2)):
    sort=data4[data4['index_test'] == indekss2].sort_values(by=['distance'], ascending=True)
    sort2=sort.iloc[0:6]
    clp=sort2.class_pred.values
    cp2.append(claspred(clp))

#print(cp2)

In [52]:
print(accuracy_score(y_test, cp2))
print(confusion_matrix(y_test, cp2))
print(classification_report(y_test, cp2))

0.8524590163934426
[[30  5]
 [ 4 22]]
              precision    recall  f1-score   support

           0       0.88      0.86      0.87        35
           1       0.81      0.85      0.83        26

   micro avg       0.85      0.85      0.85        61
   macro avg       0.85      0.85      0.85        61
weighted avg       0.85      0.85      0.85        61

